server:
  port: 8686
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Okayji
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  accessTokenTime: 1 # day
  accessTokenTimeWithRemember: 14 # day

aws:
  region: ap-southeast-1
  s3:
    bucket-name: okayji
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
presigned-url:
  expiration-minutes: 10